feat: some cleanup work
mbukeRepo/the-gym-scrimba pull request #1
Opened 2023-02-20 09:03 UTC by mbukeRepo

2023-02-20 09:31 UTC, hirwaaldo1 requested changes
Everything looks good, but if you make the suggested change, it will be even better.

2023-02-20 09:31 UTC, hirwaaldo1 commented on meme-generator/src/components/Meme.jsx
>    const node = document.getElementById("meme-img");
here it will be good if you use hooks like `useRef `or `useState `instead of using getElementById

2023-02-20 09:54 UTC, IbrahimBagalwa requested changes
Well done Prince, few changes request

2023-02-20 09:54 UTC, IbrahimBagalwa commented on notes-app/src/components/Avatarbar.js
> +export default Avatarbar;
What is the usecase of this component ?

2023-02-20 09:54 UTC, IbrahimBagalwa commented on notes-app/src/App.js
>      <div className="App dark">
the text `you have no notes` you can change the color because here is white

2023-02-20 16:00 UTC, hirwaaldo1 approved these changes
LGTM

2023-02-21 09:59 UTC, IbrahimBagalwa approved these changes
LGTM 👍

2023-02-21 14:57 UTC, Ntwali-Josue approved these changes

2023-02-21 15:47 UTC, merged